### PR TITLE
Security patches for OnePlus 3 Kernel (Marshmallow)

### PR DESCRIPTION
**Pull request by NewEraCracker**
This pull request includes all security patches that should be applied on the OnePlus 3 kernel. Some of them should also be ported to 3T while others are already there.

### CODE REVIEW

**Comment by NewEraCracker** [comment]
This PR has been updated and supersedes #11, #12, #13 and #15

**Comment by libcg** [comment]
I appreciate your work but I don't think they give a flying fuck about PRs. @OnePlusOSSAdmin please prove me wrong.

**Comment by varemenos** [comment]
I doubt they even check github

**Comment by NewEraCracker** [comment]
OxygenOS 3.2.8 has been released today. Supposedly with November security patch, I bet all they did was to replace the security update month shown in GUI and nothing else.

**Comment by NewEraCracker** [comment]
This PR has been updated again, more commits added and existing re-ordered by commit date.
Tested & Working.

**Comment by NewEraCracker** [comment]
Added more security fixes taken from 3rd-party kernels.

**Comment by NewEraCracker** [comment]
I think so far I've done a good job covering all issues with possible security implications. Been backporting stuff I've found in CyanogenMod and upstream msm-3.18 kernel.

Total: 75 commits/patches. This is a lot!

**Pull request closed without merging**
